### PR TITLE
[marketmaker] possible to configure tpu retransmissions (max retries in txn opts) when sending a transaction

### PR DESCRIPTION
**Pull request by ochaloup**
There is a missing way to configure the max retries on sending transaction to RPC node. The attempt of this PR is to fix this deficiency.
What do you think @OpinionatedGeek ?

### CODE REVIEW

**Comment by OpinionatedGeek** [comment]
I like it a lot - thanks for doing this!

One thing though. The client already retries sending to the RPC node in some circumstances, so I worry 'max retries' might not be clear that this setting governs the number of retry attempts the RPC server will make when sending it to the validator, not the number of retry attempts when sending to the RPC server.

Can you think of a better name for it? All my attempts turn out long and unwieldy.

**Comment by ochaloup** [comment]
@OpinionatedGeek I see, I can try, just you know the naming is the one of the hardest issue in the computer engineering :-)
I can think of like `tpu_retransmissions` or `tpu_retries`. Would that makes sense?

**Comment by OpinionatedGeek** [comment]
`tpu_retransmissions` sounds excellent - really makes it clear to me what it sets. Many thanks for this!

**Comment by ochaloup** [comment]
@OpinionatedGeek great, thank you.
I renamed the `max retries` to `tpu retransmissions` (plus added an update on missing building calls at context builder in respect of transaction_status_collector).
Please, take a look. Thanks!

**Comment by OpinionatedGeek** [comment]
Brilliant - thanks!

**Pull request merged**
